apiVersion: apps/v1
kind: Deployment
metadata:
  name: boot-jpa-hibernate-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  boot-jpa-hibernate
  template:
    metadata:
      labels:
        app:  boot-jpa-hibernate
    spec:
      containers:
      - name:  boot-jpa-hibernate-container
        image:  boot-jpa-hibernate:v1.0
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: nome-segreto

---
apiVersion: v1
kind: Service
metadata:
  name:  boot-jpa-hibernate-service
spec:
  selector:
    app:  boot-jpa-hibernate
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080