apiVersion: apps/v1
kind: Deployment
metadata:
  name: boot-jpa-hibernate-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boot-jpa-hibernate
  template:
    metadata:
      labels:
        app: boot-jpa-hibernate
    spec:
      containers:
      - name: boot-jpa-hibernate-container
        image: boot-jpa-hibernate:v1.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        env:
          - name: DB_HOST
            value: "your-db-host"
          - name: DB_USERNAME
            value: "your-db-username"
          - name: DB_PASSWORD
            value: "your-db-password"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: boot-jpa-hibernate-service
spec:
  selector:
    app: boot-jpa-hibernate
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
